name: Docker Image react_img

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: "Creation de l'image pba dev"
      run: docker build -t react_img:v1 .
    - name: "lancement du container dev"
      run: docker run -p 8185:80 -d  react_img:v1
